volumes:
  vidly:

services:
  client:
    build: ./frontend
    ports:
      - "3000:3000"
  server:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DB_URL: mongodb://database/vidly  
  database:
    image: mongo:4.0-xenial
    ports:
      - "27017:27017"
    volumes:
      - vidly:/data/db